source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.2.1'

target 'SafeTREC' do
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport'
  ]

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

end
